### ISSUE TITLE
D;uvidas

### ISSUE THREAD

**Issue by PauloBoaventura** [flyingluscas/correios-php#12]
## Descrição detalhada
Este código esta funcionando em PHP 5, 5.6, 7.0, 7.1 ou até mesmo em 7.2 ?
São muitas dúvidas e nada pessoal... (Já deixo claro)
Este código esta nas normativas novas dos correios (2017) e que pelo visto já existe novas normativas em (2018)...
Bom, este não é o único que visualizamos que aparentemente esta tudo correto.
Mas, tenho que ser este USUÁRIO questionador, já que estamos enfrentando tantos problemas seja eles em PHP, AJAX ou qualquer impulso anterior á 2017.
E assim vem as dúvidas...

Gostaria de saber se podemos implementar este código em outras ferramentas e até mesmo em outas plataformas... 

Espero que tenhamos uma resposta satisfatória e um UPGRADE. (O que neste notamos que o upgrade é notavel).

## Contexto

Por que essa mudança é importante para você? Como você usaria isso?

Como pode beneficiar outros usuários?

## Possível implementação

Não é obrigatório, mas sugere uma idéia para implementar adição ou mudança.

## Seu ambiente

Inclua detalhes relevantes sobre o ambiente em que você identificou o bug e como reproduzi-lo.

* Vesão usada (e.g. PHP 5.6, HHVM 3):
* Sistema operacional e versão (e.g. Ubuntu 16.04, Windows 7):
* ...
* ...
S.O = Centos7 - Plesk
Php = 5.6 / 7.0

**Comment by flyingluscas** [comment]
@PauloBoaventura tudo bem? não sei se entendi muito bem o seu problema, consegue explicar melhor?

**Comment by flyingluscas** [comment]
@PauloBoaventura sim! até onde eu sei não existe nada de errado com esse pacote :)

**Comment by flyingluscas** [comment]
@PauloBoaventura vou fechar essa issue, se tiver algum problema ou dúvida pode reabrir ela ou abrir uma nova ;)
