### ISSUE TITLE
Notice error ao informar cep sem complemento

### ISSUE THREAD

**Issue by diogolimafranco** [flyingluscas/correios-php#17]
## Descrição detalhada

Ao fazer um cálculo de preço para determinado cep, caso o correios não possua o complemento definido para o endereço, a aplicação retorna um alert Notice.

O arquivo que apresenta erro esta na pasta  vendor/flyingluscas/correios-php/src/Services/ZipCode.php na linha 200. Testei com o cep 13960-000

**Comment by flyingluscas** [comment]
@diogolimafranco Obrigado por abri essa issue, vou investigar o problema e corrigir se possível ;)
