### ISSUE TITLE
Erro no calculo do Comprimento.

### ISSUE THREAD

**Issue by fernandorotermund** [flyingluscas/correios-php#21]
Porque no método "protected function length()" você não esta multiplicando o comprimento com a quantidade de itens?

**Comment by JoaoVictorSarzi** [comment]
A altura nao pode ser maior que 105 cm.
Está dando este erro SEMPRE que tem mais de 1 item

**Comment by flyingluscas** [comment]
> Porque no método "protected function length()" você não esta multiplicando o comprimento com a quantidade de itens?

@fernandorotermund Desculpe a demora para responder, não lembro exatamente o motivo, faz muito tempo que fiz isso hahaa, mas pelo pouco que lembro estava relacionado a forma como o Correios organiza os objetos, eles empilham, porque é a forma mais otimizada de se utilizar o espaço. Por isso somente peso e altura são multiplicados pela quantidade. Faz sentido?

**Comment by flyingluscas** [comment]
> A altura nao pode ser maior que 105 cm.
> Está dando este erro SEMPRE que tem mais de 1 item

@JoaoVictorSarzi Cosegue dar mais detalhes sobre o problema? como posso reproduzir o erro? Até onde sei 105cm é o limite do Correios.

**Comment by flyingluscas** [comment]
Fechando esta issue por inatividade.
