### ISSUE TITLE
Erro ERP-008

### ISSUE THREAD

**Issue by FormigTeen** [flyingluscas/correios-php#22]
Quando eu envio 1 item com a dimensão 1x1x1, ele dá o erro de ERP-008: Dimensões não Localizadas. 

Mas quando eu coloco um item com a dimensão 16x16x16 esse erro não acontece. 

Qual o caso? O Pacote não calcula o mínimo automaticamente? E quando eu precisar enviar vários itens, terei que fazer uma checagem antes para validar o valor total das dimensões e peso?

**Comment by flyingluscas** [comment]
@FormigTeen Hoje a lib não faz esse cálculo, então acaba caindo na validação de dimensões mínimas do Correios, que você pode [consultar aqui](https://www.correios.com.br/a-a-z/limites-de-dimensoes-e-peso) ;)
