### ISSUE TITLE
Consulta de preços e prazos de múltiplos serviços não está funcionando

### ISSUE THREAD

**Issue by rafaelrgb** [flyingluscas/correios-php#23]
## Descrição detalhada

A consulta de preços e prazos com múltiplos serviços já na mesma consulta, conforme indicado no README, parou de funcionar. Acredito que não seja um bug na biblioteca, mas sim uma mudança na resposta do serviços dos correios. Antes, eu realizava a consulta da seguinte forma: 

```php
$correios = new Client;

$correios->freight()
    ->origin('01001-000')
    ->destination('87047-230')
    ->services(Service::SEDEX, Service::PAC)
    ->item(16, 16, 16, .3, 1) // largura, altura, comprimento, peso e quantidade
    ->item(16, 16, 16, .3, 3) // largura, altura, comprimento, peso e quantidade
    ->item(16, 16, 16, .3, 2) // largura, altura, comprimento, peso e quantidade
    ->calculate();
```

Porém hoje de manhã essa consulta começou a retornar a seguinte resposta:

```php
array(1) {
  [0]=>
  array(12) {
    ["Codigo"]=>
    string(1) "0"
    ["Valor"]=>
    string(1) "0"
    ["PrazoEntrega"]=>
    string(1) "0"
    ["ValorMaoPropria"]=>
    string(1) "0"
    ["ValorAvisoRecebimento"]=>
    string(1) "0"
    ["ValorValorDeclarado"]=>
    string(1) "0"
    ["EntregaDomiciliar"]=>
    object(stdClass)#458 (0) {
    }
    ["EntregaSabado"]=>
    object(stdClass)#449 (0) {
    }
    ["Erro"]=>
    string(2) "99"
    ["MsgErro"]=>
    string(76) "Erro inesperado. Descrição: Máximo de 1 código de serviço por consulta."
    ["ValorSemAdicionais"]=>
    string(1) "0"
    ["obsFim"]=>
    object(stdClass)#451 (0) {
    }
  }
}
```
Note a mensagem de erro retornada pelos correios: **"Erro inesperado. Descrição: Máximo de 1 código de serviço por consulta."**. Essa mensagem aparece mesmo acessando o serviço dos correios diretamente pela url _http://ws.correios.com.br/calculador/CalcPrecoPrazo.asmx/CalcPrecoPrazo_ no meu browser.

Após identificar o problema, mudei meu código para consultar um serviço de cada vez e depois fazer o merge das respostas:

```php
$freight->services(CorreiosService::SEDEX);
$sedexFreight = $freight->calculate();
$freight->services(CorreiosService::PAC);
$pacFreight = $freight->calculate();
return array_merge($sedexFreight, $pacFreight);
```

## Contexto

Utilizo a biblioteca correios-php na minha aplicação para calcular o preço e prazo de entregas via Pac e Sedex. Essa consulta é feita diariamente pelos usuários do site. Fui supreendido essa manhã quando esse erro começou a ocorrer em todas as requisições. Decidi criar essa issue como forma de informar os mantenedores e usuários da biblioteca sobre esse problema, para que possam ser tomadas ações a fim de evitá-lo.

**Comment by flyingluscas** [comment]
@rafaelrgb Muito obrigado pela issue! Vou olhar isso assim que possível e fazer uma nova versão com a correção! ;)

**Comment by flyingluscas** [comment]
Corrigido na versão **[v2.3.4](https://github.com/flyingluscas/correios-php/releases/tag/v2.3.4)**! ;)
