### ISSUE TITLE
Sugestão de adição de método para múltiplos itens.

### ISSUE THREAD

**Issue by lucasjovencio** [flyingluscas/correios-php#27]
## Descrição detalhada

Olá, gostaria de sugerir uma adição no código para adicionar múltiplos itens de só uma vez através de um método.

## Contexto

A mudança é importante para mim porque atualmente não é possível inserir múltiplos itens de forma dinâmica. Apenas de forma estática, invocado cada método por vez.

Como pode beneficiar outros usuários?

Adicionando multiplos itens de só uma vez.

## Possível implementação

``` php
    /**
     * array de arrays com Dimensões, peso e quantidade do items.
     * @param  array|arrays $items
     *
     * @return self
     */
    public function items($items)
    {
        foreach($items as $item){
            $this->items[] = [
                'width'     => $item[0],
                'height'    => $item[1],
                'length'    => $item[2],
                'weight'    => $item[3],
                'quantity'  => $item[4],
            ];
        }
        return $this;
    }
```
### Calculando
``` php
    $correios = new Client;
    $items = [
        [10, 10, 15, .5, 1 ], // largura, altura, comprimento, peso e quantidade
        [10, 10, 15, .5, 1 ], // largura, altura, comprimento, peso e quantidade
        [10, 10, 15, .5, 1 ], // largura, altura, comprimento, peso e quantidade
        [10, 10, 15, .5, 1 ], // largura, altura, comprimento, peso e quantidade
        [10, 10, 15, .5, 1 ], // largura, altura, comprimento, peso e quantidade
        [10, 10, 15, .5, 1 ] // largura, altura, comprimento, peso e quantidade
    ];
    $correios->freight()
        ->origin('01001-000')
        ->destination('87047-230')
        ->services(Service::SEDEX, Service::PAC)
        ->items($items) 
        ->calculate();
```
## Seu ambiente

PHP 7.3.9 (cli) (built: Aug 28 2019 09:28:48) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Windows 10 / x64

**Comment by DaniloAguiar** [comment]
neste formato voces consegue adicionar varios itens ao mesmo tempo

use FlyingLuscas\Correios\Client;
use FlyingLuscas\Correios\Service;

$correios = new Client;
$correios = $correios->freight()
    ->origin('01001-000')
    ->destination('87047-230')
    ->services(Service::SEDEX, Service::PAC);

foreach ($items as $item) {
    $correios = $correios->item($item['largura'], $item['altura'], $item['comprimento'], $item['peso'], $item['quantidade']);
}

var_dump($correios->calculate());

**Comment by antomarsi** [comment]
@flyingluscas Creio que a issue pode ser fechada, já que a duvida foi respondida.
