### ISSUE TITLE
Método de teste para verificar limites

### ISSUE THREAD

**Issue by ViniciusFernando13** [flyingluscas/correios-php#28]
Estou num caso onde preciso adicionar vários itens, mas me deparei com o erro de dimensões fora do limite dos correios, pensei em atribuir o envio a uma variável qualquer, adicionar o item e usar o calculate() para simular o erro, caso erro criar uma nova entrega, só que mesmo em outra variável o Client é o mesmo e o item ainda fica naquela entrega.
Teria como simular o mesmo ou verificar se o próximo item cabe na entrega?

**Comment by flyingluscas** [comment]
> Estou num caso onde preciso adicionar vários itens, mas me deparei com o erro de dimensões fora do limite dos correios, pensei em atribuir o envio a uma variável qualquer, adicionar o item e usar o calculate() para simular o erro, caso erro criar uma nova entrega, só que mesmo em outra variável o Client é o mesmo e o item ainda fica naquela entrega.
> Teria como simular o mesmo ou verificar se o próximo item cabe na entrega?

@ViniciusFernando13 Consegue dar mais detalhes do problema? talvez adicionar alguns trechos de código exemplificando? :)

**Comment by claudineireal** [comment]
@flyingluscas  Estou com mesmo problema, foi implementado em nosso site, porém quando selecionamos uma quantidade de 8 produtos nessas dimensões e pesos ele não calcula
Com 8 produtos no carrinho com as dimensões e pesos ( Largura: 15 Altura: 15 comprimento: 20  peso: 500g ) o correios não calcula o valor.
Teria uma solução?
Ah, ótimo trabalho :)

**Comment by Leandrosv** [comment]
@flyingluscas @claudineireal @ViniciusFernando13 , se passaram alguns meses, mas caso não tenham achado ainda a solução, eu alterei uma parte do código e para mim deu certo!
Meu produtos são pequenos, então estou me baseando por tamanhos de caixas de papelão.
Se vocês conseguirem se basearem por tamanhos de caixas, alterem essa parte aqui:
<code>
<?
//subistituir essa
protected function height()
    {
        return array_sum(array_map(function ($item) {
            return $item['height'] * $item['quantity'];
        }, $this->items));
    }
//por essa.
protected function height()
    {
        return max(array_map(function ($item) {
            return $item['height'];
        }, $this->items));
    }
 ?>
</code>
Eu fiz isso e funcionou. Ai no carrinho de compras fiz validações:
<code>
$qntProd;//quantidade do carrinho;
if($qntProd <= 2){
 lib...
}else if(($qntProd >=3)&& ($qntProd <=7)){
lib...
}
</code>
fiz isso até 50 produtos que é o limite de peso dos correios.
estou tentando bolar uma função para não repetir tanto código, mas sou programador novato, então estou com certa dificuldade nesta questão. Mas espero que se não conseguiram resolver, possam usar esta solução. 
Abraços.

**Comment by Alysonkm** [comment]
Tem um bug na hora que ele calcula items mais pesados onde o valor ultrapassa os mil reais. Ex:
Array
(
    [0] => Array
        (
            [name] => Sedex
            [code] => 4014
            [price] => 1.555
            [deadline] => 7
            [error] => Array
                (
                )

        )

    [1] => Array
        (
            [name] => PAC
            [code] => 4510
            [price] => 802.1
            [deadline] => 14
            [error] => Array
                (
                )

        )

)

No caso o sedex é 1555 e o pac 802,10 por conta do ponto que existe nos dois valores, na hora de utilizar um formatador de moeda, ele n sabe quem é decimal ou quem é milhar.
Se eu falor ponto é milhar, o pac vira 802 mil, se eu falo que é decimal, o sedex vira 1,55. Vou ter que fazer uma "gambiarra" pra validar esses valores. Seria interessante isso ja vir formatado em um padrão.
