### ISSUE TITLE
Calcular frete com CEPs diferentes na mesma compra.

### ISSUE THREAD

**Issue by marcelloinfoweb** [flyingluscas/correios-php#29]
## Descrição detalhada

Como seria possível calcular vários produtos com CEPs diferentes e fazer a soma no final?

## Contexto

Estou tentando implementar em um módulo de frete do Opencart para dropshipping.

**Comment by antomarsi** [comment]
Creio que nesta situação, teria que fazer várias requisições e somar os valores.

**Comment by flyingluscas** [comment]
@marcelloinfoweb Recomendo seguir a sugestão do @antomarsi ;)
