### ISSUE TITLE
Problema ao calcular cep com área restrita

### ISSUE THREAD

**Issue by web1989** [flyingluscas/correios-php#30]
Estou tendo problemas de obter cotação com alguns CEPs um deles é 13.203-541  alguém sabe como contornar isso?

**Comment by rodrigopeixotobr** [comment]
Pelo que sei isso é uma mensagem dos Correios e não do pacote. 
E creio que o atributo _deadline_ do retorno já está com os dias a mais somados.
Não tem o que fazer ao meu ver.

**Comment by flyingluscas** [comment]
> Estou tendo problemas de obter cotação com alguns CEPs um deles é 13.203-541 alguém sabe como contornar isso?

Consegue dar mais detalhes sobre o problema?

**Comment by web1989** [comment]
Já foi corrigido, obrigado
