### ISSUE TITLE
Dimensões mínimas dos correios ser tratado na lib

### ISSUE THREAD

**Issue by ticovix** [flyingluscas/correios-php#31]
![image](https://user-images.githubusercontent.com/12449764/93623917-d8357400-f9b5-11ea-8c87-9fcf400e0bfc.png)

Olá Lucas! Tive que fazer uma extensão da class Freght, pois o cliente tem produtos com tamanho menor do que os correios pedem. No inicio eu limitava o tamanho dos produtos com o mínimo necessário, porém passei a pensar se isso não teria que ser feito ao calcular todas as dimensões para envio para API. Então passei a limitar as dimensões mínimas para 1, porém quando um cliente adicionava apenas o produto com as dimensões menores no carrinho e calculava o frete, retornava erro na API dos Correios. Para contornar, tive que adicionar esse item pra definir um mínimo na largura, altura e comprimento.

Eu poderia não limitar no cadastro do produto e apenas adicionar os tamanhos mínimos dos correios no banco, porém com a soma da altura e comprimento, isso seria refletido no valor passado para o cliente, certo?

Acha que posso estar fazendo algo errado para ter surgido essa necessidade? Ou acha que isso seria necessário implementar na lib?

**Comment by flyingluscas** [comment]
@ticovix Lembre-se que você não pode considerar apenas as dimensões do produto, precisa considerar as dimensões dele na embalagem que será enviado, por isso o tamanho mínimo dos Correios, se você só calcular usando as dimensões do produto você estará informando para o consumidor um valor de frete que será diferente quando o lojista for despachar o produto. ;)

**Comment by flyingluscas** [comment]
@ticovix Vou fechar a issue mas caso tenha alguma outra dúvida sinta-se a vontade para reabrir ;)
