### ISSUE TITLE
Atualizar para Guzzle 7, e poder usar no Laravel 8

### ISSUE THREAD

**Issue by isaquesb** [flyingluscas/correios-php#33]
## Descrição detalhada

Laravel 8 requer guzzle 7

## Contexto

Por que essa mudança é importante para você? Como você usaria isso?
Pra que possa ser usado no Laravel 8

Como pode beneficiar outros usuários?
Poderao usar no Laravel 8

## Possível implementação

Testar com Guzzle 7 e Atualizar o composer.json

## Seu ambiente

Inclua detalhes relevantes sobre o ambiente em que você identificou o bug e como reproduzi-lo.

PHP 7.4
Laravel 8

**Comment by flyingluscas** [comment]
@isaquesb Vou dar uma olhada nisso esse fim de semana! Valeu pela sugestão 🚀

**Comment by flyingluscas** [comment]
Feito! 🚀

**Comment by isaquesb** [comment]
Show @flyingluscas ! Vlw!!

**Comment by marcelowu** [comment]
possive integra para  bagisto ecommerce?
 tem esse pluguins , https://github.com/cagartner/bagisto-correios , mas ta com erros no calculo nas medidas e pesos .

https://bagisto.com/en/how-to-create-custom-shipping-method-in-bagisto/
