### ISSUE TITLE
Composer PHP incompatível

### ISSUE THREAD

**Issue by sangiorgi** [flyingluscas/correios-php#39]
Hoje baixei o Composer última versão e quando rodo a instalação me aparece um erro de versão de PHP incompatível com a versão deles.
Gostaria de saber se isso é algum erro na minha máquina ou se será corrigido.

**Comment by flyingluscas** [comment]
@sangiorgi Consegue dar mais detalhes? Qual versão do PHP você está usando? Qual versão do Composer você está usando? Qual comando você executou que te retornou erro? Qual foi a mensagem exata do erro?

**Comment by sangiorgi** [comment]
Olá.

 

php version 8.02

 

O comando e o erro estão abaixo:

 



 

Quanto ao composer trata-se da última versão disponível.

Baixei ontem.

 

Obrigado.

 

De: lucas notifications@github.com <mailto:notifications@github.com>  
Enviada em: quarta-feira, 10 de março de 2021 17:06
Para: flyingluscas/correios-php <correios-php@noreply.github.com>
Cc: sangiorgi <asangiorgi@gmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [flyingluscas/correios-php] Composer PHP incompatível (#39)

 

@sangiorgi <https://github.com/sangiorgi>  Consegue dar mais detalhes? Qual versão do PHP você está usando? Qual versão do Composer você está usando? Qual comando você executou que te retornou erro? Qual foi a mensagem exata do erro?

**Comment by sangiorgi** [comment]
![erro](https://user-images.githubusercontent.com/22790538/110695820-15dac300-81c9-11eb-93aa-861a5fb7282f.jpg)

**Comment by flyingluscas** [comment]
@sangiorgi O pacote ainda não suporta PHP 8, ainda preciso testar algumas coisas para garantir que tudo esteja funcionando da melhor forma, em breve farei uma release do pacote com suporte para versão 8.

**Comment by sangiorgi** [comment]
Entendo.

Seria bom, entretanto, colocar um aviso com especificações de versionamento das dependências.

Apenas uma crítica construtiva.

Obrigado de todo modo.

 

De: lucas <notifications@github.com> 
Enviada em: quarta-feira, 10 de março de 2021 20:21
Para: flyingluscas/correios-php <correios-php@noreply.github.com>
Cc: sangiorgi <asangiorgi@gmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [flyingluscas/correios-php] Composer PHP incompatível (#39)

 

@sangiorgi <https://github.com/sangiorgi>  O pacote ainda não suporta PHP 8, ainda preciso testar algumas coisas para garantir que tudo esteja funcionando da melhor forma, em breve farei uma release do pacote com suporte para versão 8.
