### ISSUE TITLE
Calculo com Varios Itens

### ISSUE THREAD

**Issue by elvispdosreis** [flyingluscas/correios-php#5]
Existe opção para adicionar o numero do contrato?
O que acontece quando um pacote excede o peso e o volume, ele automaticamente cria um novo pacote.

**Comment by flyingluscas** [comment]
@elvispdosreis Sim, existe uma forma de passar o número do contrato, você pode utilizar o método `setCredentials` da classe `Freight`, sobre o peso e o volume, atualmente quando os itens da classe `Cart` ultrapassam os limites dos Correios nada acontece, ainda é feita a requisição de forma normal, e o Correios simplesmente retorna os erros, dizem que os itens estão fora do limite.
